aws/urls.py
from django.urls import path,include,re_path
from django.conf.urls import url
from django.views.generic import RedirectView
from . import views

"""
From DJRF tutorial 3, Class based views
"""
app_name = 'aws'

urlpatterns = [
    path('',views.index,name='index'),
    ]

lockdoor/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('aws/', include(('aws.urls', 'aws'),namespace='aws')),
]

aws/forms.py
from django import forms

class PostForm(forms.Form):
         post = forms.CharField(label='')

aws/views.py
from django.shortcuts import render
# Create your views here.
import boto3
from dateutil.tz import tzutc
import datetime
import os


# session = boto3.Session(profile_name='default')

session = boto3.Session(region_name=os.environ['AWS_DEFAULT_REGION'],
                            aws_access_key_id=os.environ['AWS_ACCESS_KEY_ID'],
                            aws_secret_access_key=os.environ['AWS_SECRET_ACCESS_KEY'])

def get_ec2_info():
    ec2 = session.client('ec2')
    ec2_resource = boto3.resource('ec2')
    instances = ec2.describe_instances()
    Items = instances['Reservations']
    ec2_assets = []
    for item in Items:
        data = []
        instance_id = item['Instances'][0]['InstanceId']
        data.append(instance_id)
        try:
            pub_ip = item['Instances'][0]['PublicIpAddress']
            data.append(pub_ip)
        except:
            pub_ip = 'none'
            data.append(pub_ip)
        try:
            sgId = item['Instances'][0]['SecurityGroups'][0]['GroupId']
            data.append(sgId)
            security_group = ec2_resource.SecurityGroup(sgId)
            Item = security_group.ip_permissions
            group_acl = []
            for sg_items in Item:
                acl = []
                try:
                    acl.append(sg_items['FromPort'])
                except:
                    acl.append('All')
                try:
                    acl.append(sg_items['IpProtocol'])
                except:
                    acl.append('All')
                for ace in sg_items['IpRanges']:
                    range = []
                    range.append(ace['CidrIp'])
                    acl.append(range)
                group_acl.append(acl)
            data.append(group_acl)
        except:
            sgId = 'none'
            data.append(sgId)
        try:
            name = item['Instances'][0]['PublicDnsName']
            data.append(name)
        except:
            name = item['Instances'][0]['PrivateDnsName']
            data.append(name)
        ec2_assets.append(data)
    return (ec2_assets)

def get_elb_info():
    elbv2 = session.client('elbv2')
    instances = elbv2.describe_load_balancers()
    elbv2_resource = boto3.client('elbv2')
    Items = instances['LoadBalancers']
    elb_assets = []
    for item in Items:
        data = []
        instance_id = item['LoadBalancerArn']
        data.append(instance_id)
        try:
            pub_ip = item['Scheme']
            data.append(pub_ip)
        except:
            pub_ip = 'none'
            data.append(pub_ip)
        try:
            sgId = item['SecurityGroups']
            data.append(sgId)
        except:
            sgId = 'none'
            data.append(sgId)
            security_group = elbv2_resource.SecurityGroup(sgId)
            Item = security_group.ip_permissions
            group_acl = []
            for sg_items in Item:
                acl = []
                try:
                    acl.append(sg_items['FromPort'])
                except:
                    acl.append('All')
                try:
                    acl.append(sg_items['IpProtocol'])
                except:
                    acl.append('All')
                range = []
                for ace in sg_items['IpRanges']:
                    range.append(ace['CidrIp'])
                acl.append(range)
                group_acl.append(acl)
            data.append(group_acl)
        try:
            name = item['DNSName']
            data.append(name)
        except:
            name = "None"
            data.append(name)
        elb_assets.append(data)
    return (elb_assets)

def get_rds_info():
    rds = session.client('rds')
    instances = rds.describe_db_instances()
    rds_resource = boto3.client('rds')
    Items = instances['DBInstances']
    rds_assets = []
    for item in Items:
        data = []
        instance_id = item['DBInstanceIdentifier']
        data.append(instance_id)
        try:
            pub_ip = item['Endpoint']['Address']
            data.append(pub_ip)
        except:
            pub_ip = 'none'
            data.append(pub_ip)
        try:
            sgId = item['VpcSecurityGroups'][0]['VpcSecurityGroupId']
            data.append(sgId)
        except:
            sgId = 'none'
            data.append(sgId)
            Item = rds.describe_db_security_groups()
            # Item = security_group.ip_permissions
            group_acl = []
            for sg_items in Item:
                acl = []
                try:
                    acl.append(sg_items['FromPort'])
                except:
                    acl.append('All')
                try:
                    acl.append(sg_items['IpProtocol'])
                except:
                    acl.append('All')
                range = []
                for ace in sg_items['IpRanges']:
                    range.append(ace['CidrIp'])
                acl.append(range)
                group_acl.append(acl)
            data.append(group_acl)
        try:
            name = item['DBInstanceIdentifier']
            data.append(name)
        except:
            name = "None"
            data.append(name)
        rds_assets.append(data)
    return (rds_assets)


def index(request):
    current_user = request.user.id
    elb_data = get_elb_info()
    ec2_data = get_ec2_info()
    rds_data = get_rds_info()
    context = {
        'ec2_data': ec2_data,
        'rds_data': rds_data,
        'elb_data': elb_data,
    }
    return render(request, 'aws/index.html', context)

aws/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>

  {% block title %}<title>Instances Status</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- <link href="minimal-table.css" rel="stylesheet" type="text/css"> -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <!-- Add additional CSS in static file -->
  {% load static %}
  <script
  src="https://code.jquery.com/jquery-3.4.1.js"
  integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
  crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

  <!-- Font Awesome -->
      <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

      <!-- Moment.js -->
      <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.23.0/moment.min.js" integrity="sha256-VBLiveTKyUZMEzJd6z2mhfxIqz3ZATCuVMawPZGzIfA=" crossorigin="anonymous"></script>

      <!-- Tempus Dominus Bootstrap 4 -->
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/css/tempusdominus-bootstrap-4.min.css" integrity="sha256-XPTBwC3SBoWHSmKasAk01c08M6sIA5gF5+sRxqak2Qs=" crossorigin="anonymous" />
      <script src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/js/tempusdominus-bootstrap-4.min.js" integrity="sha256-z0oKYg6xiLq3yJGsp/LsY9XykbweQlHl42jHv2XTBz4=" crossorigin="anonymous"></script>
      <script src="{% static 'aws/javascript/default.js' %}"></script>
</head>
<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2">
      {% block sidebar %}
        <ul class="sidebar-nav">
          <li><a href="{% url 'aws:index' %}">Home</a></li>
        </ul>
     {% endblock %}
      </div>
      <div class="col-sm-10 ">{% block content %}{% endblock %}</div>
    </div>
  </div>

  <!-- <script src="/static/js/search.js"></script> -->
  <link rel="stylesheet" href="{% static 'css/style.css' %}">

</body>
</html>